CREATE TABLE agent_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    task_key VARCHAR(128) NOT NULL UNIQUE,
    task_type VARCHAR(64) NOT NULL,
    original_task_type VARCHAR(64) NULL,
    model_name VARCHAR(128) NULL,
    saved_at TIMESTAMP NULL,
    prompt_text TEXT NULL,
    input_file VARCHAR(512) NULL,
    task_message TEXT NULL,
    attempt_count INT NULL,
    stopped_by_user BOOLEAN NULL,
    completed BOOLEAN NULL,
    task_state VARCHAR(64) NULL,
    resumable BOOLEAN NULL,
    resume_key VARCHAR(128) NULL,
    failure_reason TEXT NULL,
    token_input INT NULL,
    token_output INT NULL,
    parsed BOOLEAN NULL,
    result_payload_json LONGTEXT NOT NULL,
    raw_text LONGTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lead_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    external_lead_id VARCHAR(128) NULL,
    dedupe_key VARCHAR(64) NOT NULL UNIQUE,
    title VARCHAR(512) NOT NULL,
    normalized_title VARCHAR(512) NULL,
    url VARCHAR(1000) NULL,
    source_name VARCHAR(255) NULL,
    source_domain VARCHAR(255) NULL,
    source_bucket VARCHAR(64) NULL,
    organization_name VARCHAR(255) NULL,
    lead_category VARCHAR(64) NULL,
    current_stage VARCHAR(128) NULL,
    is_actionable_now BOOLEAN NULL,
    should_enter_pool BOOLEAN NULL,
    pool_entry_tier VARCHAR(64) NULL,
    opportunity_signal_class VARCHAR(128) NULL,
    category_reason TEXT NULL,
    description LONGTEXT NULL,
    publish_time TIMESTAMP NULL,
    publish_time_raw VARCHAR(128) NULL,
    publish_time_confidence DOUBLE NULL,
    within_time_window BOOLEAN NULL,
    time_window_status VARCHAR(64) NULL,
    scenario_tags_json LONGTEXT NULL,
    evidence_summary_json LONGTEXT NULL,
    recommended_technologies_json LONGTEXT NULL,
    related_links_json LONGTEXT NULL,
    latest_follow_up_action TEXT NULL,
    latest_suggested_action TEXT NULL,
    status VARCHAR(64) NULL,
    expiry_status VARCHAR(64) NULL,
    latest_screening_task_key VARCHAR(128) NULL,
    latest_investigation_task_key VARCHAR(128) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lead_score (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    lead_id BIGINT NOT NULL UNIQUE,
    scenario_fit_score DOUBLE NULL,
    ai_fit_score DOUBLE NULL,
    opportunity_maturity_score DOUBLE NULL,
    screening_score DOUBLE NULL,
    total_score DOUBLE NULL,
    deep_analysis_score DOUBLE NULL,
    evidence_strength_score DOUBLE NULL,
    raw_composite_score DOUBLE NULL,
    composite_score DOUBLE NULL,
    score_reason TEXT NULL,
    suggested_action TEXT NULL,
    score_time TIMESTAMP NULL,
    last_task_key VARCHAR(128) NULL,
    score_payload_json LONGTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lead_score_lead FOREIGN KEY (lead_id) REFERENCES lead_info (id)
);

CREATE TABLE lead_deep_analysis (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    lead_id BIGINT NOT NULL UNIQUE,
    source_continuity LONGTEXT NULL,
    similar_case_summary LONGTEXT NULL,
    landing_case_summary LONGTEXT NULL,
    policy_support_summary LONGTEXT NULL,
    budget_support_summary LONGTEXT NULL,
    competition_and_delivery_judgement LONGTEXT NULL,
    deep_analysis_conclusion LONGTEXT NULL,
    deep_analysis_score DOUBLE NULL,
    evidence_strength_score DOUBLE NULL,
    suggested_action TEXT NULL,
    ai_value_summary LONGTEXT NULL,
    ai_risks_json LONGTEXT NULL,
    timeline_json LONGTEXT NULL,
    related_links_json LONGTEXT NULL,
    source_links_by_type_json LONGTEXT NULL,
    screening_snapshot_json LONGTEXT NULL,
    final_recommendation LONGTEXT NULL,
    analysis_time TIMESTAMP NULL,
    last_task_key VARCHAR(128) NULL,
    raw_payload_json LONGTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lead_analysis_lead FOREIGN KEY (lead_id) REFERENCES lead_info (id)
);

CREATE TABLE agent_task_result (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    agent_task_id BIGINT NOT NULL,
    lead_id BIGINT NULL,
    result_type VARCHAR(64) NOT NULL,
    source_bucket VARCHAR(64) NULL,
    rank_order INT NULL,
    title VARCHAR(512) NULL,
    payload_json LONGTEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_result_task FOREIGN KEY (agent_task_id) REFERENCES agent_task (id),
    CONSTRAINT fk_task_result_lead FOREIGN KEY (lead_id) REFERENCES lead_info (id)
);

CREATE INDEX idx_lead_info_category ON lead_info (lead_category);
CREATE INDEX idx_lead_info_status ON lead_info (status);
CREATE INDEX idx_lead_info_pool_entry_tier ON lead_info (pool_entry_tier);
CREATE INDEX idx_agent_task_saved_at ON agent_task (saved_at);
